import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Chat from "./page";
import createChat from "../actions/createChat";
import GetMessages from "../actions/getMessages";
import ChatNav from "./components/chatNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ChatLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full h-screen bg-blue-00 lg:overflow-hidden">
      <ChatNav />
      <div className="flex w-full mx-auto items-center justify-center content-center">
        <div className="h-max w-full py-16 lg:py-4 bg-blue-00">{children}</div>
      </div>
    </div>
  );
}
