import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContext from "./context/AuthContext";
import getCurrentUser from "./actions/getCurrentUser";
import NavBar from "../../components/navBar";
import { Toaster } from "react-hot-toast";
import { Montserrat } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContext>
        <body>
          <div className="flex flex-col h-screen justify-between">
            <Toaster />
            {/* <NavBar /> */}
            {children}
          </div>
        </body>
      </AuthContext>
    </html>
  );
}
